({
    tables: {
        'voltage_sample': {
            name: 'voltage_sample',
            description: 'voltage measured from a device',
            primaryKey: 'start',
            columns: [
                {name: 'start', type: '.google.protobuf.Timestamp', nullable: false},
                {name: 'stop', type: '.google.protobuf.Timestamp', nullable: true},
                {name: 'mean', type: 'TYPE_DOUBLE', nullable: true},
                {name: 'standard_deviation', type: 'TYPE_DOUBLE', nullable: true,
                 description: '*sample* standard deviation'}
            ]
        },
        'voltage_sample_raw_values': {
            name: 'voltage_sample_raw_values',
            description: "here's the array",
            columns: [
                {name: 'id',
                 type: '.google.protobuf.Timestamp',
                 nullable: false,
                 foreignKey: {
                     table: 'voltage_sample',
                     column: 'start'
                 },
                 description: String}, // description is generated by Okra
                {name: 'value',
                 type: 'TYPE_DOUBLE',
                 nullable: true,
                 description: String} // description is generated by Okra
            ],
            // index on the column that's a foreign key to voltage_sample.start
            indices: [{
                columns: ['id']
            }]
        }
    },
    legends: {
        // There's one legend for each message type. We have just one message
        // type, ".stats.VoltageSample", and so there's just one legend that
        // tells us the relationship between that type's fields and these
        // tables' columns.
        '.stats.VoltageSample': {
            messageTypeName: '.stats.VoltageSample',
            tableName: 'voltage_sample',
            fieldSources: [
                {fieldName: 'start', columnName: 'start'},
                {fieldName: 'stop', columnName: 'stop'},
                {fieldName: 'mean', columnName: 'mean'},
                {fieldName: 'standardDeviation', columnName: 'standard_deviation'},
                // `rawValues` is the array-valued field, and so its field
                // source has a `tableName` property. The `columnName` then
                // tells you which column in _that_ table has the value(s).
                {fieldName: 'rawValues', tableName: 'voltage_sample_raw_values',
                 columnName: 'value'}
            ]
        }
    }
})
